### PR TITLE
chore(readme): add wip note

### PR DESCRIPTION
**Pull request by papb**
I was happy to see this module and immediately ran `npm i p-sync` but it's not out yet.

By the way you should take it quickly... Release a 0.1.0 version or something just to guarantee the ownership of this name.

-----
[View rendered README.md](https://github.com/papb/p-sync/blob/patch-1/README.md)

### CODE REVIEW

**Comment by Richienb** [comment]
@papb 5 years ago, `psync` was taken. Now, with npm anti-typosquatting measures, I can't publish to `p-sync`. For now, I'm trying to get hold of `psync` so I can then ask npm to unpublish it so I can publish `p-sync`.

**Comment by papb** [comment]
@Richienb Hmmm... I see... However this PR should be merged anyway, no?

**Comment by papb** [comment]
Nice! :tada:

**Comment by Richienb** [comment]
@papb `p-syncy` is now out!

**Pull request merged**
